### PR TITLE
Specifying golang(>1.10) to use

### PR DESCRIPTION
**Pull request by edwardstudy**

### CODE REVIEW

**Comment by HeavyWombat** [comment]
I am not sure if I understand correctly. Could you please explain the issue again? Currently, we use Travis to compile `havener` with Go versions `1.8`, `1.9`, `1.10`, `1.11`. The actual binary compile for the GitHub release section is done using Go `1.11`.

**Comment by HeavyWombat** [comment]
Thanks for the hint that the `make` target `clean` is causing issues with older Go versions. I decided to fix it in the `Makefile` with commit b5fd45ff.

**Comment by HeavyWombat** [comment]
@edwardstudy Now that I re-read your comment and the proposed change in the README. I think just mentioning in the README that Golang is required with a version of `1.8` or greater is enough. The dependencies are covered by `vendor` and mentioned in the `version` command. At the moment, I do not see a reason to lay them out in the README in more detail, maybe later.

**Comment by edwardstudy** [comment]
OK. I see.

**Comment by HeavyWombat** [comment]
Again, thank you very much for your input!

**Pull request merged**
